Nursery/Models/ApplicationDbContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace Nursery.Models
{
    public class ApplicationDbContext:DbContext
    {
        public ApplicationDbContext() : base("NurceryConn")
        {

        }
        public DbSet<Nursery> nurseries { get; set; }
        public DbSet<Category> categories { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder); 

            modelBuilder.Entity<Nursery>()
                .HasIndex(x => x.SKU_NO)
                .IsUnique();
        }




    }
}

Nursery/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Nursery.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }    
    }
}

Nursery/Models/Nursery.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Nursery.Models
{
    public class Nursery
    {
        public int Id { get; set; }
        public int SKU_NO { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsAvailable { get; set; }
        public DateTime CreatedDate { get; set; }

        public Category Category { get; set; }
        public int CategoryId { get; set; }

    }
}

Nursery/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Nursery.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Nursery/Controllers/NurceryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Nursery.Models;

namespace Nursery.Controllers
{
    public class NurceryController : Controller
    {
        private readonly ApplicationDbContext _dbcontext = null;

        public NurceryController()
        {
            _dbcontext = new ApplicationDbContext();
        }
        // GET: Nurcery
        public ActionResult Index()
        {
            var NurceryItem=_dbcontext.nurseries.ToList();
            return View(NurceryItem);
        }

        public ActionResult Detais(int id)
        {
            var items = _dbcontext.nurseries.FirstOrDefault(x => x.Id == id);

            if(items != null)
            {
                return View(items); 
            }
            return HttpNotFound();
        }
        //GET
        [HttpGet]
        public ActionResult create()
        {
            
            var categories = _dbcontext.categories.ToList();
            ViewBag.categories = categories;
            return View();
        }

        //[HttpPost]
        //public ActionResult create()
        //{
        //    return View();
        //}

    }
}

Nursery/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Nursery/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Nursery/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Nursery/Views/Nurcery/Detais.cshtml
@model Nursery.Models.Nursery
@{
    ViewBag.Title = "Detais";
}

<h2>Details</h2>

<h3>Product Name:@Model.Name</h3>
<ul>

    <li><b>Quantity :</b>@Model.Description</li>

</ul>

Nursery/Views/Nurcery/Index.cshtml
@model IEnumerable<Nursery.Models.Nursery>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div class="container">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <h2>Product Details</h2>

            <table class="table table-striped table-hover">
                <tr class="table-dark">
                    <th>Id</th>
                    <th>Plants Name</th>

                </tr>
                @foreach (var plnt in Model)
                {
                    <tr>
                        <td>@plnt.Id</td>
                        <td>@Html.ActionLink(plnt.Name, "Detais", "Nurcery", new { id = plnt.Id }, null)</td>

                    </tr>
                }
            </table>
        </div>
    </div>
</div>

Nursery/Views/Nurcery/create.cshtml
@using Nursery.Models
@model Nursery
@{
    ViewBag.Title = "create";
}

<h2>Adding new Product</h2>
<hr/>

<div class="container">
    <div class="row">
        @using (Html.BeginForm())
        {
            <div class="mb-2">
                @Html.LabelFor(p => p.SKU_NO)
                @Html.TextBoxFor(p => p.SKU_NO, new { @class = "form-control" })
            </div>
            <div class="mb-2">
                @Html.LabelFor(p => p.Name)
                @Html.TextBoxFor(p => p.Name, new { @class = "form-control" })
            </div>
            <div class="mb-2">
                @Html.LabelFor(p => p.Description)
                @Html.TextBoxFor(p => p.Description, new { @class = "form-control" })
            </div>
            <div class="mb-2">
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault">
                        @Html.LabelFor(p => p.IsAvailable)
                    </label>
                </div>


                @*@Html.LabelFor(p => p.IsAvailable)
        @Html.CheckBoxFor(p => p.IsAvailable)*@

            </div>
            <div class="mb-2">
                @Html.LabelFor(p => p.CategoryId)
                @Html.DropDownListFor(p => p.CategoryId, new SelectList(ViewBag.Categories, "Id", "Name"), new {@class ="form-select"})
            </div>
            <div class="mb-2">
                <button type="submit" class="btn btn-primary">Save</button>
                <button type="reset" class="btn btn-primary">Reset</button>
            </div>

        }
    </div>
</div>

Nursery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">

        <div class="container-fluid">

            <div class="navbar-brand">

                @Html.ActionLink("My Project", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

            </div>

            <div class="collapse navbar-collapse">

                <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                    <li class="nav-item">@Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link" })</li>

                    <li class="nav-item">@Html.ActionLink("Add New", "create", "Nurcery", null, new { @class = "nav-link" })</li>

                    <li class="nav-item">@Html.ActionLink("Product Details", "Index", "Nurcery", null, new { @class = "nav-link" })</li>

                </ul>

            </div>

        </div>

    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @*@Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>